### PR TITLE
Add in the ability for DI onto view models methods

### PR DESCRIPTION
**Pull request by JamesFreeman**
This PR adds the ability to Dependency Inject against any of the method calls against the ViewModel.

```php 
public function getTweets(TwitterService $twitterService)
{
    return $twitterService->get();
}
```

### CODE REVIEW

**Comment by JamesFreeman** [comment]
Hey @brendt, 

I've pushed up my changes now, It was pretty tricky to get both the callable function calls and the DI method calls working together but I think I've come up with a nice solution. Does this address your concerns on the view method calls?

**Comment by brendt** [comment]
Can you elaborate how the solution works?

**Comment by JamesFreeman** [comment]
When the VM is converting the methodToVariable, it will get all of the parameters that are passed in. It will then work out if that variable is typed, if it is it will try to figure out if it's a class and if it is it will resolve that class from the container. 

It will then work out if the method is callable by seeing if there is a mismatch in parameter counts. 

I wasn't 100% sure on the best way for this to implemented, I'm happy to take some guidance and go back to the drawing board if needed.

**Comment by nickfls** [comment]
@JamesFreeman will that work with container's `$this->app->when(VM::class)->needs(...)>give(..)`?

**Comment by JamesFreeman** [comment]
Laravel should handle that from there side, I'm not really interacting with the container other than passing the class into `app();`

**Comment by brendt** [comment]
> It will then work out if that variable is typed, if it is it will try to figure out if it's a class and if it is it will resolve that class from the container.

That's not a fool proof, unfortunately. Imagine this method (taken from the readme):

```
class PostViewModel extends ViewModel
{
    public function formatDate(Carbon $date): string
    {
        return $date->format('Y-m-d');
    }
}
```

`Carbon` is a class, but shouldn't be resolved from the container. 

The only viable solution I can think of is to introduce attributes:

```
class PostViewModel extends ViewModel
{
    public function formatDate(
        Carbon $date,
        #[FromContainer] DateFormatter $dateFormatter,
    ): string {
        // …
    }
}
```

But at this point I'm wondering whether the feature is worth it, especially when the same is already possible with constructor injection.

**Comment by JamesFreeman** [comment]
I think my code will deal with that situation because it's being passed in via a callable method, I'll spend some time this afternoon adding that Carbon callable instance as a test, at the very least we can get that test merged in.

**Comment by JamesFreeman** [comment]
I spent some time on this yesterday evening and it looks like it doesn't work correctly. I think the fact that VM has invokable methods makes this sort of implementation near impossible without it being super messy/hacky. 

What are your thoughts @brendt?

**Comment by brendt** [comment]
I really appreciate the effort but think that we've hit a road block here. Maybe we can reconsider it in the next major version or by introducing attributes; but I feel like it's a lot of work for little benefit, especially since DI is possible via the constructor already.

So I'm going to close this one.

**Pull request closed without merging**
